name: PR actions
on:
  pull_request:
    branches:
      - v1.x
jobs:
  e2e-tests:
    name: E2E test
    runs-on: ubuntu-latest
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          yarn global add vtex
          echo "$(yarn global bin)" >> $GITHUB_PATH
      - run: vtex
      - uses: actions/checkout@v2
        with:
          repository: hiagolcm/search-tests-temp
          path: search-tests
      - uses: actions/checkout@v2
        with:
          path: ioapp
      - run: yarn
        working-directory: search-tests
      - run: node ci/createSession.js --appkey=${{ secrets.APP_KEY }} --apptoken=${{ secrets.APP_TOKEN }}
        working-directory: search-tests
      - run: |
          vtex workspace create test${{ github.sha }}
          vtex workspace use test${{ github.sha }}
      - run: vtex link --no-watch
        working-directory: ioapp
      - uses: cypress-io/github-action@v2
        with:
          config-file: cypress.json
          working-directory: search-tests
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.RECORD_KEY }}
          VTEX_WORKSPACE: test${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_BRANCH: ${{ github.ref }}
          COMMIT_INFO_SHA: ${{ github.sha }}
          COMMIT_INFO_REMOTE: ${{ github.repository }}
          COMMIT_INFO_MESSAGE: ${{ env.commitmsg }}
          COMMIT_INFO_AUTHOR: ${{ github.actor }}
      - uses: actions/github-script@v3
        if: failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'E2E tests failed. Go to https://dashboard.cypress.io/projects/qvjzx1 to check the recordings.'
            })
